name       : libopenmpt
version    : 0.6.0
release    : 6
source     :
    - https://lib.openmpt.org/files/libopenmpt/src/libopenmpt-0.6.0+release.autotools.tar.gz : a1fc61283864624d820836ce4d37af4907476cdcd31f6f09a23ba271500025ab
license    : BSD-3-Clause
component  : multimedia.library
homepage   : https://lib.openmpt.org/libopenmpt/
summary    : OpenMPT-based module player library
description: |
    libopenmpt is a cross-platform C++ and C library to decode tracked music files into a raw PCM audio stream.
builddeps  :
    - pkgconfig(libmpg123)
    - pkgconfig(vorbisfile)
setup      : |
    %configure \
        --disable-examples \
        --disable-openmpt123 \
        --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rfv $installdir/usr/share/
