name       : libopenmpt
version    : 0.5.11
release    : 4
source     :
    - https://lib.openmpt.org/files/libopenmpt/src/libopenmpt-0.5.11+release.autotools.tar.gz : 4469e095948d976cff4d7eb1936a27e9947624e49b160c29fcb246911ba5a4b0
license    : BSD-3-Clause
component  : multimedia.library
homepage   : https://lib.openmpt.org/libopenmpt/
summary    : OpenMPT-based module player library
description: |
    libopenmpt is a cross-platform C++ and C library to decode tracked music files into a raw PCM audio stream.
builddeps  :
    - pkgconfig(libmpg123)
    - pkgconfig(vorbisfile)
setup      : |
    %configure \
        --disable-examples \
        --disable-openmpt123 \
        --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rfv $installdir/usr/share/
