name       : libopenmpt
version    : 0.5.8
release    : 1
source     :
    - https://lib.openmpt.org/files/libopenmpt/src/libopenmpt-0.5.8+release.autotools.tar.gz : 29e2c21174b73f67f2ba5ee76808d62f182b130e4f704ee2d9ae8283982d8acd
license    : BSD-3-Clause
component  : multimedia.library
homepage   : https://lib.openmpt.org/libopenmpt/
summary    : OpenMPT-based module player library
description: |
    libopenmpt is a cross-platform C++ and C library to decode tracked music files into a raw PCM audio stream.
builddeps  :
    - pkgconfig(libmpg123)
    - pkgconfig(vorbisfile)
setup      : |
    %configure \
        --disable-examples \
        --disable-openmpt123 \
        --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rfv $installdir/usr/share/
