name       : libopenmpt
version    : 0.6.2
release    : 7
source     :
    - https://lib.openmpt.org/files/libopenmpt/src/libopenmpt-0.6.2+release.autotools.tar.gz : 50c0d62ff2d9afefa36cce9f29042cb1fb8d4f0b386b81a0fc7734f35e21e6b6
license    : BSD-3-Clause
component  : multimedia.library
homepage   : https://lib.openmpt.org/libopenmpt/
summary    : OpenMPT-based module player library
description: |
    libopenmpt is a cross-platform C++ and C library to decode tracked music files into a raw PCM audio stream.
builddeps  :
    - pkgconfig(libmpg123)
    - pkgconfig(vorbisfile)
setup      : |
    %configure \
        --disable-examples \
        --disable-openmpt123 \
        --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rfv $installdir/usr/share/
